-- Executar no banco sistema_db

CREATE TABLE IF NOT EXISTS dev_log_erros (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nivel ENUM('INFO','WARNING','ERROR','CRITICAL') NOT NULL DEFAULT 'ERROR',
  arquivo VARCHAR(100) DEFAULT NULL,
  mensagem TEXT,
  usuario VARCHAR(100) DEFAULT NULL,
  ip VARCHAR(50) DEFAULT NULL,
  criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_nivel (nivel),
  INDEX idx_criado (criado_em)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS dev_log_acoes (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  usuario VARCHAR(100) NOT NULL,
  acao VARCHAR(100) NOT NULL,
  modulo VARCHAR(50) DEFAULT NULL,
  descricao TEXT,
  ip VARCHAR(50) DEFAULT NULL,
  criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_usuario (usuario),
  INDEX idx_acao (acao),
  INDEX idx_criado (criado_em)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS dev_invasoes (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  arquivo VARCHAR(100) DEFAULT NULL,
  usuario_tentativa VARCHAR(100) DEFAULT NULL,
  ip VARCHAR(50) DEFAULT NULL,
  user_agent VARCHAR(500) DEFAULT NULL,
  tipo ENUM('SEM_LOGIN','PERMISSAO_INSUFICIENTE','SESSAO_EXPIRADA') NOT NULL DEFAULT 'SEM_LOGIN',
  criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_ip (ip),
  INDEX idx_criado (criado_em)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
